name: Sync Create-Frontron Project

on:
  push:
    paths:
      - 'packages/create-frontron/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.email "andongmin94@gmail.com"
        git config --global user.name "안동민"

    - name: Sync to Create-Frontron Repository
      run: |
        git remote add create-frontron-repo https://github.com/Frontron/create-frontron.git
        git fetch create-frontron-repo
        git checkout main
        git merge create-frontron-repo/main --allow-unrelated-histories
        git push create-frontron-repo main --force
      shell: /usr/bin/bash -e {0}
