name: Sync Docs Directory

on:
  push:
    paths:
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.email "andongmin94@gmail.com"
        git config --global user.name "안동민"

    - name: Sync to Docs Repository
      run: |
        git remote add docs-repo https://github.com/Frontron/frontron-docs.git
        git fetch docs-repo
        git checkout main
        git merge docs-repo/main --allow-unrelated-histories
        git push docs-repo main --force
      shell: /usr/bin/bash -e {0}